// Generated by CoffeeScript 1.7.1
(function() {
  var disable, enable;

  disable = function(parentElement) {
    return $(parentElement).css({
      "overflow-y": "hidden"
    });
  };

  enable = function(parentElement) {
    return $(parentElement).css({
      "overflow-y": "scroll"
    });
  };

  $.fn.scrollify = function(parentElement) {
    if (parentElement == null) {
      parentElement = "body";
    }
    return $(this).hover(function() {
      if ($(this).get(0).scrollHeight > $(this).get(0).clientHeight) {
        return disable(parentElement);
      }
    }, function() {
      return enable(parentElement);
    });
  };

}).call(this);
